AllCops:
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
Style/OpenStructUse:
  Exclude:
    - 'spec/integration/*'
Style/ClassAndModuleChildren:
  Exclude: 
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*_spec.rb'
    - 'lib/**/*_spec.rb'
    - '*.gemspec'
Metrics/MethodLength:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude: 
    - 'spec/**/*'
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
